In [24]:
from surprise import KNNBasic,AlgoBase
import seaborn
import matplotlib.pyplot as plt
import matplotlib.pylab as pl
from sklearn.cluster import DBSCAN
import numpy as np
from sklearn import metrics

In [2]:
%store -r euc_dist
%store -r cos_dist

In [15]:
euc_dist[2][2]

0.0

In [12]:
mydbscan = DBSCAN(metric='precomputed',eps=20)

In [22]:
mydbscan.fit(euc_dist)
core_samples_mask = np.zeros_like(mydbscan.labels_, dtype=bool)
core_samples_mask[mydbscan.core_sample_indices_] = True
labels = mydbscan.labels_
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [34]:
np.sort(euc_dist)

array([[  0.        ,   6.55743852,   8.24621125, ...,  60.43177972,
         61.13918547,  62.14499175],
       [  0.        ,   7.        ,   9.94987437, ...,  58.64298765,
         58.8812364 ,  59.51470407],
       [  0.        ,   4.47213595,   7.81024968, ...,  53.57238094,
         54.60769177,  57.13142743],
       ..., 
       [  0.        ,   8.1240384 ,   9.59166305, ...,  53.27288241,
         54.39669108,  54.45181356],
       [  0.        ,   6.32455532,   6.55743852, ...,  67.48333128,
         68.78226516,  69.05794668],
       [  0.        ,   6.63324958,   7.        , ...,  51.65268628,
         52.31634544,  52.63078947]])

In [7]:
sim_options = {'name': 'eucledian',
               'user_based': False  # compute  similarities between items
               }
algo = KNNBasic(sim_options=sim_options)

In [55]:
#np.sort(euc_dist)
np.argsort(euc_dist)
#euc_dist[0][119]

array([[  0, 119,  50, ..., 800, 903, 932],
       [  1,   4, 136, ..., 938, 985, 982],
       [  2,   5,  95, ..., 927, 903, 932],
       ..., 
       [997, 999, 856, ...,  11,  28,  72],
       [998, 976, 919, ...,  90,  28, 101],
       [999, 910, 949, ...,  39,  71,  42]])

In [52]:
algo.train(trainset=euc_dist)

AttributeError: 'numpy.ndarray' object has no attribute 'n_items'

In [16]:
mydbscan.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,